[package]
name = "candle-wgpu-kernels-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = {version="1.0", features = []}
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
fs2 = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"